# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20171201_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
