# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_player_owner'),
        ('games', '0009_auto_20171201_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='game',
            name='owner',
        ),
        migrations.AddField(
            model_name='game',
            name='player_p1',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_player', to='user.Player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='player_p2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_player', to='user.Player'),
        ),
    ]
