# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_game_players_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='game',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='games.Game'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='move',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
