# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_auto_20171202_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='board',
            field=models.CharField(max_length=5000),
        ),
    ]
