# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20171204_0025'),
        ('games', '0013_auto_20171204_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('won', models.BooleanField(default=False)),
                ('owner', models.BooleanField()),
                ('first', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile')),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='player_p1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_game', to='games.Player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_p2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guested_game', to='games.Player'),
        ),
        migrations.AlterField(
            model_name='move',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Player'),
        ),
    ]
