# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_auto_20171204_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='players_counter',
            new_name='players_count',
        ),
    ]
