# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 02:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_auto_20171204_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='move',
            old_name='x_coordinate',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='move',
            old_name='y_coordinate',
            new_name='y',
        ),
    ]
