# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20171201_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='owner',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
