# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_auto_20171204_2057'),
        ('user', '0005_auto_20171204_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
